add 128 and 124 proficiency exams
hkn-alpha/wiki pull request #15
Opened 2023-07-10 00:23 UTC by rzig

2023-07-11 23:01 UTC, alex-m-zhang requested changes
A few changes, but nothing major. @lnguy7 is there anything else we want to add for proficiency exam sections? I think Ryan covered everything but I would like your opinion too.

2023-07-11 23:01 UTC, alex-m-zhang commented on docs/Proficiency Exams/index.md
> +For students coming in with prior experience or who are looking to graduate early, proficiency exams offer a way to skip classes. Proficiency exams are generally offered at the beginning of each seme
There is some penalty for failing - iirc you can't retake proficiency exams too many times. Not sure if that's worth adding here though.

2023-07-11 23:01 UTC, alex-m-zhang commented on docs/Proficiency Exams/CS124.md
> +## Who Should Take It
It -> the Proficiency Exam (just to make it clear)

2023-07-11 23:01 UTC, alex-m-zhang commented on docs/Proficiency Exams/CS128.md
> +## Who Should Take It
It -> Proficiency Exam

2023-07-16 04:08 UTC, lnguy7 approved these changes
LGTM CS128 prof exam sounds like pain

2023-07-16 05:38 UTC, alex-m-zhang approved these changes
LGTM!

2023-07-16 05:38 UTC, merged