Misc wiki changes
hkn-alpha/wiki pull request #18
Opened 2023-07-14 01:52 UTC by alex-m-zhang

Lots of changes to index.md files.

2023-07-16 04:04 UTC, lnguy7 requested changes
I have gripes about these names lol

2023-07-16 04:04 UTC, lnguy7 commented on docs/Course Wiki/Taking X versus Y/index.md
I hate this name can we call it "Course Equivalents" or sth

2023-07-16 04:04 UTC, lnguy7 commented on docs/Course Wiki/Taking X with Y/index.md
Same with this can it be called "Course Combos"?

2023-07-16 05:43 UTC, alex-m-zhang commented on docs/Course Wiki/Taking X versus Y/index.md
We cannot, or it will be the first page on the course wiki instead of the course offerings (everything is listed in alphabetical order).

2023-07-16 05:43 UTC, alex-m-zhang commented on docs/Course Wiki/Taking X with Y/index.md
We cannot, or it will be the first page on the course wiki instead of the course offerings (everything is listed in alphabetical order).

2023-07-16 18:29 UTC, rzig requested changes

2023-07-16 18:29 UTC, rzig commented on docs/Course Wiki/Taking X versus Y/index.md
> +Ever found two courses that appear to be the exact same but probably not? Fear not! This section of the course wiki is dedicated to advising students about the difference between two courses (and whi
but probably not -> but probably aren't

2023-07-16 18:29 UTC, rzig commented on docs/Course Wiki/Taking X versus Y/index.md
> +Ever found two courses that appear to be the exact same but probably not? Fear not! This section of the course wiki is dedicated to advising students about the difference between two courses (and whi
(and which one...) -> and which is the right fit for them

2023-07-16 18:29 UTC, rzig commented on docs/Course Wiki/index.md
> +We would love your help making Dr. Everitt's Neighborhood better; log in and start contributing! We manage contributions on [GitHub](https://github.com/hkn-alpha/wiki). Please feel free to open a pul
rm "log in and..."

2023-07-16 18:29 UTC, rzig commented on docs/Course Wiki/index.md
> +If you see a course review that is outdated, let us know. If you think the author was crazy and the opinions are totally wrong, help us fix it. If you want to write a review for a course that doesn't
input by opening an issue on GitHub

2023-07-16 18:29 UTC, rzig commented on docs/More Advice/index.md
> +This page contains some random advice collected from wise students who have already graduated. Feel free to peruse these at your leisure.
rm the feel free sentence

2023-07-16 18:29 UTC, rzig commented on docs/index.md
> +For information on core and elective ECE courses, as well as related courses from other departments, head to the [Course Wiki](/Course%20Wiki) tab. We've compiled several example schedules (i.e. how
curriculum graph is for cs too right?

2023-07-22 00:12 UTC, rzig approved these changes

2023-07-24 02:16 UTC, lnguy7 commented on docs/Course Wiki/Taking X versus Y/index.md
Equivalent Courses?

2023-07-24 02:16 UTC, lnguy7 commented
Also fix conflict plz

2023-08-01 03:05 UTC, rzig commented
Is this good to merge?

2023-08-17 04:00 UTC, lnguy7 approved these changes
LGTM

2023-08-17 04:00 UTC, merged