Filled out ECE210.md
hkn-alpha/wiki pull request #21
Opened 2023-07-17 02:47 UTC by aidanrodgers

I filled out the ECE210 page.

2023-07-21 19:05 UTC, alex-m-zhang requested changes
Few changes here and there. I'll let Lucas comment more on the content since he took the class more recently (although from what I remember this is accurate).

2023-07-21 19:05 UTC, alex-m-zhang commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
> +[ECE110](ECE110.md), [PHYS212](../PHYS%20Course%20Offerings/PHYS212.md), and credit or concurrent registration in [MATH285](../MATH%20Course%20Offerings/MATH285.md) are listed as official prerequisit
"as ECE210 heavily involves solving differential equations" -> "as ECE210 relies heavily on the ability to solve differential equations."

2023-07-21 19:05 UTC, alex-m-zhang commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
> +Students interested in electrical engineering should take ECE210 as soon as possible. It is strongly recommended for electrical engineering majors to take this course by the second semester of their
One thing to add: How do you take this course asap? Should people go for the MATH classes asap? etc.

2023-07-21 19:05 UTC, alex-m-zhang commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
> +An additional weekly honors section led by upperclassmen is also available to students who want to use Python for course relevant material. The honors section consists of a weekly one hour tutorial/d
Also might be good to mention it is helpful to take ECE314, the accompanying lab for ECE313 as well.

2023-07-21 19:05 UTC, alex-m-zhang commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
>  ## Course Structure
Out of curiosity: is this course structure finally stable? Or is it still changing from semester to semester?

If the former, no changes necessary. If the latter, maybe make a note of that.

2023-07-21 19:05 UTC, alex-m-zhang commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
> +This course is currently directed by Professor Kudeki.  Instructors vary from semester to semester and typically have backgrounds in a wide variety of fields of electrical engineering, namely signal
Might be worth mentioning that Alvarez pretty much teaches this every semester.

2023-07-21 19:05 UTC, alex-m-zhang commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
> +Many past exams are posted on the course website, dating back to 2007.  Going through the past exam problems is one of the best ways to study for the midterm and final exams.
Add: "however, simply looking over the solutions for past exams will not help at all. Past exams are truly useful if they are taken in an exam environment (and only checking solutions after truly attempting the problem).

2023-07-21 23:45 UTC, aidanrodgers commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
>  ## Course Structure
Looks like some things have changed between FA22 and SP23, so I'll make a note of that.

2023-07-22 00:29 UTC, alex-m-zhang approved these changes
LGTM! Waiting on @lnguy7.

2023-07-24 02:14 UTC, lnguy7 commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
>  ## Prerequisites
Isn't 110 a prereq to this course?

2023-07-24 02:14 UTC, lnguy7 commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
>  ## Course Structure
It might be a good idea to add patch notes to each class as they try to balance everything year to year

2023-07-24 02:15 UTC, lnguy7 commented
LTM besides those 2 comments

2023-07-24 02:26 UTC, aidanrodgers commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
>  ## Prerequisites
Yes, I mentioned 110

2023-07-24 02:28 UTC, aidanrodgers commented on docs/Course Wiki/ECE Course Offerings/ECE210.md
>  ## Course Structure
Wdym, should I describe what has changed between the past two semesters?

2023-07-26 15:20 UTC, alex-m-zhang commented
Lucas to write Patch Notes for course structure: week of 7/31.

2023-08-17 04:00 UTC, merged