Xavier/ece220
hkn-alpha/wiki pull request #48
Opened 2023-09-17 19:44 UTC by xavierrouth

hi guys :) 🐈

2023-10-03 22:59 UTC, xavierrouth commented
I need someone who has taken this class more recently to help fill in the tips section / review in general. Most of the other content should be good.

2023-10-03 23:01 UTC, xavierrouth commented
idk how to resolve this.

2023-10-03 23:02 UTC, xavierrouth commented
idk how to fix this

2023-10-03 23:12 UTC, rzig requested changes
few nitpicks otherwise lgtm

2023-10-03 23:12 UTC, rzig commented on docs/Course Wiki/ECE Course Offerings/ECE220.md
> +- [ECE120](ECE120.md)
add name of ece120

2023-10-03 23:12 UTC, rzig commented on docs/Course Wiki/ECE Course Offerings/ECE220.md
> +Don't go to lecture or lab.
so true

2023-10-03 23:12 UTC, rzig commented on docs/Course Wiki/ECE Course Offerings/ECE220.md
> +Don't go to lecture or lab.
but maybe explain why lecture/lab aren't that useful

2023-10-03 23:12 UTC, rzig commented on docs/Course Wiki/ECE Course Offerings/ECE220.md
> +Taking ECE 220 opens up some higher level courses to highly motivated undergrads. Keep in mind you need to have completed your [junior eligibility requirements](https://ece.illinois.edu/academics/ugr
no space between ECE and 220

2023-10-09 14:22 UTC, rzig requested changes

2023-10-09 14:22 UTC, rzig commented on docs/Course Wiki/ECE Course Offerings/ECE220.md
> +Taking ECE220 opens up some higher level courses (that aren't explicitly required) to highly motivated undergrads. Keep in mind you need to have completed your [junior eligibility requirements](https
maybe move course list to first sentence - "motivated undergrads, such as ECE408, CS431, ..."

2023-10-09 14:22 UTC, rzig commented on docs/Course Wiki/ECE Course Offerings/ECE220.md
>  - [Compiler Explorer](https://www.xavierrouth.com/lc3compiler)
compiler explorer :star_struck:

2023-10-10 14:55 UTC, rzig approved these changes

2023-10-10 14:56 UTC, merged