Create PHYS211
hkn-alpha/wiki pull request #62
Opened 2023-10-15 19:53 UTC by taoweih

2023-10-15 20:07 UTC, lnguy7 requested changes

2023-10-15 20:07 UTC, lnguy7 commented on docs/Course Wiki/PHYS Course Offerings/PHYS211.md
> +Recently, this course has been taught by Professor Tim Stelzer and Professor Jorge Leite Noronha Jr.
Do we have any info on these two profs?

2023-10-15 20:07 UTC, lnguy7 commented on docs/Proficiency Exams/CS173.md
> +# CS173
Make sure to label as 128 not173

2023-10-22 19:26 UTC, lnguy7 approved these changes

2023-10-22 19:38 UTC, aidanrodgers requested changes
Minor changes.

2023-10-22 19:38 UTC, aidanrodgers commented on docs/Course Wiki/PHYS Course Offerings/PHYS211.md
> +Ratations and Waves can be difficult for students who are seeing them for the first time. Understanding of how to use the formulas on the formula sheet is extremely helpful for dealing with those top
"Ratations and Waves" -> "Rotations and waves", "Understanding of" -> "Understanding"

2023-10-22 19:38 UTC, aidanrodgers commented on docs/Course Wiki/PHYS Course Offerings/PHYS211.md
> +The official prerequisites to PHYS211 is credit or concurrent registration in [MATH231](MATH231.md)(While MATH231 is listed as a corequisite for PHYS211, no heavy calculation will be used in PHYS211)
"The official prerequisites to PHYS211 is" -> "The official prerequisites to PHYS211 are"
Make "while" lowercase, put a space after MATH231.

2023-10-22 19:56 UTC, aidanrodgers requested changes
Last thing, sorry

2023-10-22 19:56 UTC, aidanrodgers commented on docs/Course Wiki/PHYS Course Offerings/PHYS211.md
> +Ratations and waves can be difficult for students who are seeing them for the first time. Understanding how to use the formulas on the formula sheet is extremely helpful for dealing with those topics
"Rotations" spelled incorrectly

2023-10-22 20:00 UTC, aidanrodgers approved these changes
Looks good, thanks!

2023-10-22 20:01 UTC, merged