Added PHYS211 to Proficiency Exams
hkn-alpha/wiki pull request #64
Opened 2023-10-15 21:15 UTC by V-001

2023-10-18 21:41 UTC, aidanrodgers requested changes
Looks good, just some typos/small changes.

2023-10-18 21:41 UTC, aidanrodgers commented on docs/Proficiency Exams/PHYS211.md
> +If you have a solid bakcground in Physics Mechanics at the level of at least AP Physics C, then you should consider taking the proficiency exam for PHYS221. ECE students (and most engineering student
Typo on "background".  PHYS221 -> PHYS211.

2023-10-18 21:41 UTC, aidanrodgers commented on docs/Proficiency Exams/PHYS211.md
> +[PHYS211 (University Physics: Mechanics)](../Course%20Wiki/CS%20Course%20Offerings/PHYS211.md) is the first required physics course in the Electrical and Computer Engineering curriculum, and covers t
mechanical physics -> mechanics, typo on "fundamentals"

2023-10-18 21:41 UTC, aidanrodgers commented on docs/Proficiency Exams/PHYS211.md
> +The exam consists of both multiple choice and fill in the blank questions given through Prairietest. Typically, you are provided a [formula sheet](https://courses.physics.illinois.edu/phys211/fa2023/
explain what IC stands for

2023-10-18 21:41 UTC, aidanrodgers commented on docs/Proficiency Exams/PHYS211.md
> +The profiency exam (in recent past) has been similar to the final exam for this course. Focus on making sure you understand the fundementals of the concepts and use the practice exams avaiable throug
typo on "proficiency", "available".  Change "fundamentals of the concepts" to "fundamental concepts"

2023-10-18 21:41 UTC, aidanrodgers commented on docs/Proficiency Exams/PHYS211.md
> +Practice exams for previous semester's finals should be publically available through the course website for PHYS211. You should be able to access this through the physics department website under the
semester's -> semesters', publically -> publicly.

2023-10-18 21:41 UTC, aidanrodgers commented on docs/Proficiency Exams/PHYS211.md
> +If you pass the PHYS211 proficiency exam, congrats! You have a fundemental understanding of mechancial physics and are ready to tackle the next physics challenge that comes your way.
typo on "fundamental", "mechancial physics" -> "mechanics".  Mention PHYS212.

2023-10-25 00:03 UTC, rzig approved these changes

2023-10-25 00:09 UTC, aidanrodgers approved these changes

2023-10-25 00:09 UTC, merged