Added CS498GC
hkn-alpha/wiki pull request #97
Opened 2023-12-18 08:07 UTC by kteal

Added CS498GC, also fixed the CS course list

2023-12-18 14:00 UTC, aidanrodgers requested changes
small changes

2023-12-18 14:00 UTC, aidanrodgers commented on docs/Course Wiki/CS Course Offerings/CS498GC.md
> +- [MATH221](../MATH%20Course%20Offerings/MATH221.md), MATH225 or equivalent, [MATH285](../MATH%20Course%20Offerings/MATH285.md) or equivalent, STAT400 or equivalent, [CS225](./CS225.md)
Separate each prerequisite in separate bullet points, and link each page, even if they don't exist yet.  STAT400 will be in "other course offerings".  Also link them on first mention in the next paragraph

2023-12-18 14:00 UTC, aidanrodgers commented on docs/Course Wiki/CS Course Offerings/CS498GC.md
> +CS498GC focuses on the software development of mobile robotics, so it is important to have a solid understanding of data structures and algorithms. Although the official prerequisite is only CS225, t
prerequisite misspelled

2023-12-18 14:00 UTC, aidanrodgers commented on docs/Course Wiki/CS Course Offerings/CS498GC.md
> +- [Fall 2023 Syllabus](https://uofi.app.box.com/s/ag4j39jnall7g5lr3xvrxb771cf6hnpb)
don't link website/syllabus if they will change in future semesters

2023-12-24 06:32 UTC, kteal commented
since the cs courses have been updated since I made this branch, the list is out of date again. should I merge master into this branch and then add those classes to the list or can we tackle that in a future PR?

2023-12-24 12:17 UTC, aidanrodgers commented
> since the cs courses have been updated since I made this branch, the list is out of date again. should I merge master into this branch and then add those classes to the list or can we tackle that in a future PR?
Don’t worry about this, I can update it.

2023-12-24 12:19 UTC, aidanrodgers approved these changes

2023-12-24 12:20 UTC, merged